<?php
$jieqiBlocks[11]=array('bid'=>0, 'blockname'=>'周点击榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'周点击榜', 'vars'=>'weekvisit,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
$jieqiBlocks[12]=array('bid'=>0, 'blockname'=>'月点击榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'月点击榜', 'vars'=>'monthvisit,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
$jieqiBlocks[13]=array('bid'=>0, 'blockname'=>'总点击榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'总点击榜', 'vars'=>'allvisit,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);

$jieqiBlocks[21]=array('bid'=>0, 'blockname'=>'周推荐榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'周推荐榜', 'vars'=>'weekvote,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
$jieqiBlocks[22]=array('bid'=>0, 'blockname'=>'月推荐榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'月推荐榜', 'vars'=>'monthvote,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
$jieqiBlocks[23]=array('bid'=>0, 'blockname'=>'总推荐榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'总推荐榜', 'vars'=>'allvote,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);

$jieqiBlocks[31]=array('bid'=>0, 'blockname'=>'周鲜花榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'周鲜花榜', 'vars'=>'weekflower,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
$jieqiBlocks[32]=array('bid'=>0, 'blockname'=>'月鲜花榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'月鲜花榜', 'vars'=>'monthflower,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
$jieqiBlocks[33]=array('bid'=>0, 'blockname'=>'总鲜花榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'总鲜花榜', 'vars'=>'allflower,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);

$jieqiBlocks[41]=array('bid'=>0, 'blockname'=>'周月票花榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'周月票花榜', 'vars'=>'weekvipvote,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
$jieqiBlocks[42]=array('bid'=>0, 'blockname'=>'月月票花榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'月月票花榜', 'vars'=>'monthvipvote,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
$jieqiBlocks[43]=array('bid'=>0, 'blockname'=>'总月票花榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'总月票花榜', 'vars'=>'allvipvote,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);

$jieqiBlocks[51]=array('bid'=>0, 'blockname'=>'收藏榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'收藏榜', 'vars'=>'goodnum,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);

$jieqiBlocks[61]=array('bid'=>0, 'blockname'=>'字数榜', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'字数榜', 'vars'=>'words,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);

$jieqiBlocks[71]=array('bid'=>0, 'blockname'=>'编辑推荐', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'编辑推荐', 'vars'=>'toptime,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);

$jieqiBlocks[81]=array('bid'=>0, 'blockname'=>'最新入库', 'module'=>'article', 'filename'=>'block_articlelist', 'classname'=>'BlockArticleArticlelist', 'side'=>-1, 'title'=>'最新入库', 'vars'=>'postdate,10,0,0,0,0', 'template'=>'marticle_topnum.html', 'contenttype'=>4, 'custom'=>0, 'publish'=>3, 'hasvars'=>1);
?>