<?php
$jieqiConfigs['system'] = array (
  'onlinetime' => 1800,
  'maxmessages' => 50,
  'maxdaymsg' => 0,
  'maxfriends' => 50,
  'checkcodelogin' => '1',
  'usegd' => '0',
  'regtimelimit' => 0,
  'usernamelimit' => '0',
  'registeremail' => '0',
  'avatardir' => 'avatar',
  'avatarurl' => '',
  'avatartype' => '.gif .jpg .jpeg .png',
  'avatarcut' => '1',
  'avatarsize' => 1000,
  'inaddvipvote' => 100,
  'outaddvipvote' => 0,
  'fakeuserinfo' => '',
  'fakeuserpage' => '',
  'mailtype' => '2',
  'maildelimiter' => '1',
  'mailserver' => 'smtp.qq.com',
  'mailport' => 465,
  'mailauth' => '1',
  'mailfrom' => '377653@qq.com',
  'mailuser' => '377653@qq.com',
  'mailpassword' => '123456',
  'posttitlemax' => 60,
  'postintervaltime' => 0,
  'postdenytimes' => '',
  'postaudittimes' => '',
  'postdenywords' => '【公告】',
  'postreplacewords' => '文革',
  'postminsize' => 0,
  'postmaxsize' => 0,
  'postdenyrubbish' => '0',
  'postcheckcode' => '0',
  
);

?>