<?php
$jieqiConfigs['system'] = array (
  'onlinetime' => 1800,
  'maxmessages' => 50,
  'maxdaymsg' => 0,
  'maxfriends' => 50,
  'regtimelimit' => 0,
  'usernamelimit' => '0',
  'registeremail' => '0',
  'avatardir' => 'avatar',
  'avatarurl' => '',
  'avatartype' => '.gif .jpg .jpeg .png',
  'avatarcut' => '1',
  'avatarsize' => 2000,
  'inaddvipvote' => 100,
  'lowegoldwarn' => 0,
  'channelerate' => 0,
  'channeldlimit' => 0,
  'exchangerate' => 100,
  'settlemin' => 0,
  'fakeuserinfo' => '',
  'fakeuserpage' => '',
  'mailtype' => '2',
  'maildelimiter' => '1',
  'mailencrypt' => '0',
  'mailserver' => '',
  'mailport' => 25,
  'mailauth' => '1',
  'mailfrom' => '',
  'mailuser' => '',
  'mailpassword' => '',
  'posttitlemax' => 60,
  'postintervaltime' => 0,
  'postdenytimes' => '',
  'postaudittimes' => '',
  'postdenywords' => '',
  'postreplacewords' => '',
  'postminsize' => 0,
  'postmaxsize' => 0,
  'postdenyrubbish' => '0',
  'postcheckcode' => '7',
  'postminexperience' => 0,
  'postemailverify' => '1',
);

?>